# Generated by Django 3.2.12 on 2022-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('rock', 'GENRE_ROCK'), ('jazz', 'GENRE_JAZZ'), ('blues', 'GENRE_BLUES')], default='rock', max_length=155),
        ),
        migrations.AlterField(
            model_name='album',
            name='popularity',
            field=models.CharField(choices=[('top', 'POPULARITY_TOP'), ('oldy', 'POPULARITY_OLDY')], default='top', max_length=155),
        ),
    ]
