# Generated by Django 3.2.12 on 2022-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('alias', models.CharField(max_length=155, unique=True)),
                ('band', models.CharField(max_length=155, null=True)),
                ('instrument', models.CharField(max_length=155, null=True)),
                ('status', models.CharField(choices=[('active', 'STATUS_ACTIVE'), ('retired', 'STATUS_RETIRED')], default='active', max_length=155)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
    ]
