# Generated by Django 3.2.12 on 2022-04-22 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('released', models.DateField(null=True)),
                ('single_demo', models.BooleanField(default=False)),
                ('logins', models.ManyToManyField(related_name='logins', through='playlists.Playlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
    ]
